# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - oraclejdk8

install: mvn clean package -DskipTests=true