# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8
  
# http://docs.travis-ci.com/user/build-lifecycle/  
before_install:
  - npm install -g bower  

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN

# http://docs.travis-ci.com/user/deployment/openshift/
deploy:
  provider: openshift
  user: bn@bennyn.de
  password:
    secure: QYLnsw4zVcDi+7AzwU9XUmUWn8fbHCGI9JHb1QgnDTkTNgYuUubzne98/4ez90FPJwGbvxSIg/1OFif/FgQ+fqjO1b4jPtOjaZynvR2A4w+icI4GdifoXCzIaJenwf5RHQdxbSA+WHfoHlV5v5rCQWiWjr+dlz3bXPPV8gYKHkA=
  app: jbosswildfly
  domain: welovecoding
  on: master
